#v 0.9.0
language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  
env:
  global:
    - APPLICATION_ENV=testing_phpunit

before_install:
    - composer install
    - cd tests

script: 
- ../vendor/bin/phpunit --verbose --debug --configuration phpunit.xml --coverage-text --coverage-clover=coverage.xml

after_success:
 - bash <(curl -s https://codecov.io/bash)
