#v 0.9.1
language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

services:
  - mysql
  - postgresql
 
env:
  global:
    - APPLICATION_ENV=testing_phpunit

before_install:
  - composer install
  - cd tests

before_script:
 - psql  -c "CREATE DATABASE  patapouf;" -U postgres
 - mysql -e "CREATE DATABASE  patapouf;" -u root

script: 
- ../vendor/bin/phpunit --verbose --debug --configuration phpunit.xml --coverage-text --coverage-clover=coverage.xml

after_success:
 - bash <(curl -s https://codecov.io/bash)
